FROM ubuntu:latest

LABEL author = "chencd97"
LABEL github = "https://github.com/chencd97"
LABEL version = "1.0.1"

# 安装jre
ADD OpenJDK17U-jre_x64_linux_hotspot_17.0.6_10.tar.gz /usr/local
# 设置变量
ENV JRE_HOME /usr/local/jdk-17.0.6+10-jre
ENV CLASSPATH .
ENV PATH $PATH:$JRE_HOME/bin

# 切换工作目录,进容器时的默认目录
WORKDIR /usr/local
