FROM ubuntu:latest

LABEL author="chencd97"
LABEL github="https://github.com/chencd97"
LABEL version="1.0.2"

# 安装jre
ADD OpenJDK21U-jre_x64_linux_hotspot_21.0.5_11.tar.gz /usr/local
# 设置变量
ENV JRE_HOME=/usr/local/jdk-21.0.5+11-jre
ENV CLASSPATH=.
ENV PATH=$PATH:$JRE_HOME/bin

# 切换工作目录,进容器时的默认目录
WORKDIR /home
