FROM ubuntu:latest

LABEL author="chencd97"
LABEL github="https://github.com/chencd97"
LABEL version="1.0.1"

# 安装jre
ADD jre-8u202-linux-x64.tar.gz /usr/local
# 设置变量
ENV JRE_HOME /usr/local/jre1.8.0_202
ENV CLASSPATH .
ENV PATH $PATH:$JRE_HOME/bin

# 切换工作目录,进容器时的默认目录
WORKDIR /home
