name: Docker Image CI Build and push

on:
    push:
        branches: [ "main" ]
    # 允许随时手动运行作业
    workflow_dispatch:

jobs:
    docker:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            # 运行自定义命令(测试), 文件目录 /home/runner/work/docker-image-base/docker-image-base
            - name: run custom command
              run: |
                  pwd
                  ls -al

            # - name: Build the Docker image
            #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push [jre8]
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: ./Dockerfile_ubuntu_jre8u202
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/base:ubuntu_jre8u202

            - name: Build and push [ojre17]
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: ./Dockerfile_ubuntu_ojre11
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/base:ubuntu_ojre11

            - name: Build and push [ojre17]
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: ./Dockerfile_ubuntu_ojre17
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/base:ubuntu_ojre17

            - name: Build and push [ojre21]
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: ./Dockerfile_ubuntu_ojre21
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/base:ubuntu_ojre21

            # 通知
            - name: send notification
              run: curl ${{ secrets.BARK }}/GithubAction/Docker_base项目已更新
